#!/bin/bash

orange="\033[1;33m"
green="\033[0;32m"

function color(){
    echo -e $1
}
function reset_color(){
    echo -e "\033[0m"
}

color $orange
echo "Running PHP CodeSniffer"
echo "======================="
reset_color
./vendor/bin/phpcs

color $orange
echo "Running PHP CBF"
echo "==============="
reset_color
./vendor/bin/phpcbf

color $orange
echo "PHP CBF complete"
echo "Running CodeSniffer again for manual error fixes"
last_sniff=$(./vendor/bin/phpcs)

if [ $($last_sniff | wc -l) -lt 1 ]; then
    color $green
    echo "Seems like the code is properly formatted"
    reset_color
else
    echo -e $last_sniff
fi

