#!/bin/bash
# Clearing the FFF trash script

while true; do
	read -p "Do you want to clear the trash? [y/n]" toclear
	case $toclear in
		[Yy]*	)	rm ~/.local/share/fff/trash/* -rf; break;;
		[Nn]*	)	echo "Not clearing the trash"; break;;
		*	)	echo "Please answer yes or no."
	esac
done
