#!/bin/bash

eval $(xdotool getmouselocation --shell)
if [[ $DROPDOWN_OPEN == false ]]; then
	if [[ $X > 1920 ]]; then
		i3-msg '[instance="dropdown"] scratchpad show; [instance="dropdown"] move position 3195 px 660 px' >> /dev/null
	else
		i3-msg '[instance="dropdown"] scratchpad show; [instance="dropdown"] move position 1295 px 660 px' >> /dev/null
	fi
else
	i3-msg '[instance="dropdown"] move scratchpad' >> /dev/null
fi
