#!/bin/bash

displays=$(xrandr --query | grep ' connected' | awk '{print $1}');
screen=$( echo -e $displays | tr " " "\n" | dmenu );

xsetwacom set "Wacom Intuos PT S 2 Pen stylus" MapToOutput $screen
